import oracledb

username = "ADMIN"
password = "ppPPPP__253fSEDF8675__3fcdvbj"
dsn = "adbforailowercost_high"
wallet_dir = "/home/opc/vector-playground/wallet"

print("Connecting to Oracle Database...")
try:
    connection = oracledb.connect(
        user=username, password=password, dsn=dsn,
        config_dir=wallet_dir, wallet_location=wallet_dir, wallet_password=password
    )
    print("✅ Connection successful!")
    
    with connection.cursor() as cursor:
        print("Creating and populating orders_demo table...")
        cursor.execute("drop table if exists orders_demo")
        cursor.execute("""
            create table if not exists orders_demo
                (id number generated by default on null as identity,
                product_id number,
                order_date timestamp,
                customer_id number,
                total_value number(6,2),
                order_shipped boolean,
                warranty interval year to month)""")
        cursor.execute("""
            insert into orders_demo (product_id, order_date, customer_id, total_value, order_shipped, warranty)
            values
            (12, systimestamp, 100001, 10.23, true, interval '2-0' year to month),
            (234, systimestamp, 223223, 1200.00, false, interval '1-6' year to month),
            (57, systimestamp, 238121, 110.1, True, interval '5-0' year to month),
            (2, systimestamp, 78993, 20.50, null, interval '0-6' year to month)
        """)
        
        print("Creating and populating customers_demo table...")
        cursor.execute("drop table if exists customers_demo")
        cursor.execute("""
            create table if not exists customers_demo (
                id             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                first_name     VARCHAR2(100),
                last_name      VARCHAR2(100),
                email          VARCHAR2(320),
                address        VARCHAR2(80),
                phone_number   VARCHAR2(20))
            """)
        cursor.execute("""
            insert into customers_demo (id, first_name, last_name, email, address, phone_number)
            values
            (100001, 'Dan', 'Thompson', 'dt7889@gmail.com', '10 smith street', '34454-1667'),
            (223223, 'John', 'Smith', 'jsmith@hotmail.com', 'the grove', '28902'),
            (238121, 'Janet', 'White', 'jw123@gmail.com', 'apartment 256, 120 east street', '18092-7980'),
            (78993, 'Sue', 'Gray', 'sue_gray@testmail.com', '2345 main street', '34454')
            """)
        
        print("Creating constraints...")
        cursor.execute("alter table customers_demo add (constraint customers_pk primary key (id))")
        cursor.execute("alter table orders_demo add (constraint orders_pk primary key (id))")
        cursor.execute("alter table orders_demo add (constraint orders_fk FOREIGN KEY (customer_id) REFERENCES customers_demo (id))")
        
        print("Creating customers_dv JSON Duality View...")
        cursor.execute("drop view if exists customers_dv")
        cursor.execute("""
            CREATE or REPLACE JSON RELATIONAL DUALITY VIEW customers_dv AS
                customers_demo @insert @update @delete
                {_id      : id
                FirstName       : first_name
                LastName        : last_name
                Email           : email
                Address         : address
                Phone    : phone_number
                orders : orders_demo @insert @update @delete
                [ {OrderID             : id
                    ProductID           : product_id
                    OrderDate           : order_date
                    TotalValue          : total_value
                    OrderShipped        : order_shipped
                    } ]
                }
            """)
            
        print("Creating LOAN_CHUNK table...")
        cursor.execute("drop table if exists LOAN_CHUNK")
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS LOAN_CHUNK (
                CUSTOMER_ID VARCHAR2(50),
                CHUNK_ID NUMBER,
                CHUNK_TEXT CLOB,
                CHUNK_VECTOR VECTOR
            )
        """)
        connection.commit()
    print("✅ All foundation tables and views created successfully.")
except Exception as e:
    print(f"❌ Error during database initialization: {e}")
